employee/urls.py
from django.urls import include, path, re_path
from employee.view.index_view import index
from employee.view.manage_view import manage
from employee.view.register_view import RegisterView


urlpatterns = [
    re_path(r'^$', index, name="index"),
    re_path(r'^register/$', RegisterView.as_view(), name="register"),
    re_path(r'^employee/(?P<employee_id>\d+)$', manage, name="manage"),
    re_path(r'^employee/', index, name="index_list"),
]

employee_api/urls.py
from django.urls import include, re_path
from employee_api.api_views.employee import EmployeeViewSet
from employee_api.router import EmployeeRouter

employee_router = EmployeeRouter()
employee_router.register(r'employee', EmployeeViewSet, base_name="Employee")



urlpatterns = [
    re_path(r'^', include(employee_router.urls)),
]

luizalabCodingTest/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('employee.urls')),
    re_path(r'^', include('users.urls')),
    re_path(r'^api/v1/', include('employee_api.urls')),
]

users/urls.py
from django.urls import re_path
from users.views import RegisterUserView
from django.contrib.auth.views import login, logout_then_login


urlpatterns = [
    re_path(r'^registeradmin/$', RegisterUserView.as_view(), name="registeradmin"),
    re_path(r'^login/$', login, { 'template_name' : 'login.html', 'redirect_authenticated_user': '/'}, name="login" ),
    re_path(r'^logout/$', logout_then_login, { 'login_url' : '/'}, name="logout"),
]

employee/models/employee.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=255, null=False)
    department = models.CharField(max_length=150, null=False)
    email = models.EmailField(max_length=255, null=False)

    def __str__(self):
        return str("name: {0}, email: {1}, department: {2}".format(self.name, self.email, self.department) )

    def __cmp__(self, other):
        return self.__dict__ == other.__dict__

employee/models/serializer.py
from employee.models.employee import Employee
from rest_framework import serializers

class EmployeeSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Employee
        fields = ("id", "name", 'email', 'department')

employee_api/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

employee/forms.py
from django import forms
from employee.models.employee import Employee

class RegisterUserForm(forms.Form):
  name = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  department = forms.CharField(required=True)

  def is_valid(self):
    valid = True
    if not super(RegisterUserForm, self).is_valid():
      self.add_error("Please, verify informed data")
      valid = False

    valid = self.checkUserAlreadyExists()

    return valid

  def add_error(self, message):
    errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
    errors.append(message)

  def checkUserAlreadyExists(self):
    valid = True

    user_exists = Employee.objects.filter(name=self.data['name']).exists()

    if user_exists:
      self.add_error("User with name {} already exists".format(self.data['name']))
      valid = False

    return valid

users/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
  nome = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  senha = forms.CharField(required=True)
#  telefone = forms.CharField(required=False)
#  nome_empresa = forms.CharField(required=False)

  def is_valid(self):
    valid = True
    if not super(RegistrarUsuarioForm, self).is_valid():
      self.adiciona_erro("Por favor, verifique os dados informados")
      valid = False

    user_exists = User.objects.filter(username=self.data['nome']).exists()

    if user_exists:
      self.adiciona_erro("Usuário já existente")
      valid = False
    return valid

  def adiciona_erro(self, mensagem):
    errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
    errors.append(mensagem)

employee/views.py
from django.shortcuts import render

# Create your views here.

employee_api/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.views.generic.base import View
from users.forms import RegistrarUsuarioForm

class RegisterUserView(View):
  template_name = "registeradmin.html"

  def get(self, request):
    return render(request, self.template_name)

  def post(self, request):
    form = RegistrarUsuarioForm(request.POST)
    if form.is_valid():
      dados_form = form.data
      user = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])
      user.is_superuser = True
      user.is_staff = True
      user.save()

      return redirect('index')

    return render(request, self.template_name, { 'form': form })

employee/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
	<link href="{% static "styles/main.css" %}" rel="stylesheet">
	<link href="{% static "styles/signin.css" %}" rel="stylesheet">

	<script type="text/javascript" src="{% static "scripts/vendor/jquery-1.9.1.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/vendor/jquery-validation/dist/jquery.validate.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/vendor/bootstrap-min.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/vendor/jquery.pagination.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/script.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/validate-rules.js" %}"></script>


	<title>Luizalab Employee Manager</title>
</head>
<body>
	<div class="container">
		<div class="header">
			<ul class="nav nav-pills pull-right">
				{% if has_logged_user %}
					<li class=""><a href="/admin">{{logged_profile}}</a></li>
					<li class=""><a href="{% url 'logout' %}">Logout</a></li>
				{% endif %}
			</ul>
			<h3 class="text-muted">Luizalab Employee Manager</h3>
		</div>
		<div class="row content">
			{% block body %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

employee/templates/delete_modal.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirm</h4>
      </div>
        <div class="panel-body"> Want delete <span id="username"></span>? </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" id="modal-btn-yes">Yes</button>
        <button type="button" class="btn btn-primary" id="modal-btn-no">No</button>
      </div>
    </div>
  </div>
</div>

employee/templates/index.html
{% extends "base.html" %}
{% block body %}

{% include "delete_modal.html"%}
{% include "update_modal.html"  %}

<div class="panel panel-primary">

    <div class="panel-heading clearfix">
      <h4 class="panel-title pull-left" style="padding-top: 7.5px;"><strong>Employee's List</strong></h4>
      <a href="{% url 'register' %}" class="btn btn-default btn-sm pull-right" role="button">Register Employee</a>
    </div>
    <div class="container">
        <table class="table table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>

        {% if employees_list.results %}
            {% for employee in employees_list.results %}
              <tr id="employee_{{ employee.id }}">
                <td >
                    <p class="id">
                      {{ employee.id }}
                    </p>
                </td>

                <td>
                  <p class="name">
                    {{ employee.name }}
                  </p>
                </td>
                <td>
                    <p class="email">
                      {{ employee.email}}
                    </p>
                </td>
                <td>
                  <p class="department">
                    {{ employee.department}}
                  </p>
                </td>
                {% if has_logged_user %}
                    <td>
                      <a href="#" class="update_employee btn btn-warning btn-sm pull-right" role="button">update</a>
                    </td>
                    <td><a href="#"  class=" delete_employee btn btn-danger btn-sm pull-right" role="button">delete</a></td>
                {% else %}
                    <td><a href="{% url 'login' %}"   role="button">Require loggedin user</a></td>
                {% endif %}
              </tr>
            {% endfor %}
        {% else %}
            <div class="panel-body">
              <p>Any employee register yet</p>
            </div>
        {% endif %}

        </tbody>
      </table>

      <nav aria-label="Page navigation">
          <ul class="pagination" id="pagination"></ul>
      </nav>

    </div>

</div>
<script type="text/javascript">
  $(function () {

    actual_page = 1;
    param = getUrlParameter('page')
    if ( param ){
      actual_page = parseInt( param );
    }
    var numberOfPages = Math.ceil( {{employees_list.count}} / {{ page_size}} );

    var $pagination = $('#pagination');
    var defaultOpts = {
        initiateStartPageClick: false,
        totalPages: numberOfPages,
        visiblePages: 5,
        startPage: actual_page,
        onPageClick: function (event, page) {
          paginationController(page);
        }
    };
    $pagination.twbsPagination(defaultOpts);
  });
</script>

{% endblock %}

employee/templates/register.html
{% extends "base.html" %}
{% block body %}
<form class="form-signin" role="form" action="{% url 'register' %}" method="POST">
  {% csrf_token%}
  <h3 class="form-signin-heading"> Register Employee </h3>

  <input type="text" id="id_name" value="{{ form.name.value }}" name="name" class="form-control" placeholder="Name *" required autofocus>
  <input type="email" id="id_email" value="{{ form.email.value }}" name="email" class="form-control" placeholder="Email *" required>
  <input type="text" id="id_department" value="{{ form.department.value }}" name="department" class="form-control" placeholder="Department *" required>

  <hr />

  <button class="btn primary btn-lg btn-primary btn-block" type="submit" value="login">Register</button>

  {% if form.errors %}
    <hr />
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true" >&times;</button>
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="panel-body">
          {% if field.errors %}
            <p><span>{{ field.label_tag }}</span>{{ field.errors }}</p>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <a href="/">Home</a>
</form>
{% endblock %}

employee/templates/update_modal.html
<!-- Modal -->
<div class="modal fade" id="myModalHorizontal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Update user: <span class="modal-username"></span>
                </h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">

                <form id="update_employee" class="form-horizontal" role="form">
                  {% csrf_token %}
                  <div class="form-group">
                    <label  class="col-sm-2 control-label" >ID</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" name="id" value="{{ form.id.value}}"
                      id="id" placeholder="Id *" readonly />
                    </div>
                  </div>


                  <div class="form-group">
                    <label  class="col-sm-2 control-label"
                              for="id_name">Name</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" name="name" value="{{ form.name.value}}"
                      id="id_name" placeholder="Name *" required />
                    </div>
                  </div>

                  <div class="form-group">
                    <label  class="col-sm-2 control-label"
                              for="id_email">Email</label>
                    <div class="col-sm-10">
                      <input type="email" class="form-control" name="email" value="{{ form.email.value}}"
                      id="id_email" placeholder="Email *" required  />
                    </div>
                  </div>


                  <div class="form-group">
                    <label  class="col-sm-2 control-label"
                              for="id_department">Department</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="department" value="{{ form.department.value}}"
                        id="id_department" placeholder="Department *" required  />
                    </div>
                  </div>

                </form>
            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                            Close
                </button>
                <button type="button" id="submit_form" class="btn btn-primary">
                    Save changes
                </button>
            </div>
        </div>
    </div>
</div>

users/templates/base_user.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
	<link href="{% static "styles/main.css" %}" rel="stylesheet">
	<link href="{% static "styles/signin.css" %}" rel="stylesheet">

	<script type="text/javascript" src="{% static "scripts/vendor/jquery-1.9.1.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/vendor/jquery-validation/dist/jquery.validate.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/vendor/bootstrap-min.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/vendor/jquery.pagination.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/script.js" %}"></script>
	<script type="text/javascript" src="{% static "scripts/validate-rules.js" %}"></script>


	<title>Luizalab Employee Manager</title>
</head>
<body>
	<div class="container">
		<div class="header">
			<ul class="nav nav-pills pull-right">
				{% if has_logged_user %}
					<li class=""><a href="/admin">{{logged_profile}}</a></li>
					<li class=""><a href="{% url 'logout' %}">Logout</a></li>
				{% endif %}
			</ul>
			<h3 class="text-muted">Luizalab Employee Manager [Admin Area]</h3>
		</div>
		<div class="row content">
			{% block body %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

users/templates/login.html
{% extends "base_user.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h3 class="form-signin-heading">Login System Admin</h3>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Name *" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Password *" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        <hr />
        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Loggin Error: Please, verify login/password.
          </div>
        {% endif %}

        <a href="/">home</a>
        |
        <a href="{% url 'registeradmin' %}">Add New System User </a>
    </form>

{% endblock %}

users/templates/registeradmin.html
{% extends "base_user.html" %}
{% block body %}
<form class="form-signin" role="form" action="{% url 'registeradmin' %}" method="POST">
  {% csrf_token%}
  <h3 class="form-signin-heading"> Create new system user </h3>
  <input type="text" id="id_email" value="{{ form.email.value }}" name="email" class="form-control" placeholder="Email *" required autofocus>
  <input type="text" id="id_nome" value="{{ form.nome.value }}" name="nome" class="form-control" placeholder="Name *" required>
  <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Password *" required>

  <hr />


  <button class="btn primary btn-lg btn-primary btn-block" type="submit" value="login">Register System Admin</button>

  <hr />

  {% if form.errors %}
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true" >&times;</button>
      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="panel-body">
          {% if field.errors %}
            <p><span>{{ field.label_tag }}</span>{{ field.errors }}</p>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <a href="\"> home </a> | Have a user? <a href="{% url 'login' %}">login</a>
</form>
{% endblock %}